FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY ui-operativa-base ./ui-operativa-base
COPY server.py .

RUN chmod +x server.py

CMD ["python3", "server.py"]

